services:
  app:
    image: vvviruz-command-center:v1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
