ALTER TABLE "Release" ADD COLUMN "languages" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Release" ADD COLUMN "genres" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Release" ADD COLUMN "moods" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Release" ADD COLUMN "inspirationContext" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Release" ADD COLUMN "themes" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Release" ADD COLUMN "listenerContexts" TEXT NOT NULL DEFAULT '[]';
