"use client";

import Link from "next/link";
import {useState} from "react";
import {AlertTriangle, CalendarRange, LoaderCircle, Plus} from "lucide-react";
import {adminFetch, getAdminErrorMessage} from "@/lib/admin-errors";

type Option = {id: string; displayName?: string; title?: string; artistProfileId?: string | null};
type Campaign = {id: string; name: string; platform: string; status: string; updatedAt: string; release: {id: string; title: string}; activeIntervals: Array<{confirmationStatus: string; activeStartDate: string | null; activeEndDate: string | null}>; overlaps: Array<Record<string, unknown>>};
type ListData = {page: number; pageSize: number; total: number; items: Campaign[]};

function provenance(value: string) { return value === "CONFIRMED" ? "Confirmed" : value === "SUGGESTED" ? "Suggested from evidence" : value.toLowerCase(); }

export function CampaignTimelineCenter({artists, releases, initialData}: {artists: Option[]; releases: Option[]; initialData: ListData}) {
  const [data, setData] = useState(initialData); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [filters, setFilters] = useState({releaseId: "", platform: "", status: "", activeDate: "", confirmationStatus: ""});
  const [form, setForm] = useState({artistProfileId: artists[0]?.id || "", releaseId: "", platform: "META", name: "", objective: "STREAMS", notes: "", externalCampaignId: "", externalCampaignName: ""});
  async function load() { setBusy(true); setError(""); try { const q = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => value && q.set(key.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`), value)); const result = await adminFetch<{items: Campaign[]; page: number; pageSize: number; total: number}>(`/api/analytics/campaigns?${q}`); setData(result); } catch (cause) { setError(getAdminErrorMessage(cause)); } finally { setBusy(false); } }
  async function create(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const result = await adminFetch<{campaignId: string}>("/api/analytics/campaigns", {method: "POST", headers: {"content-type": "application/json"}, body: JSON.stringify(form)}); window.location.assign(`/admin/retention-lab/campaigns/${result.campaignId}`); } catch (cause) { setError(getAdminErrorMessage(cause)); setBusy(false); } }
  const eligibleReleases = releases.filter((release) => !form.artistProfileId || !release.artistProfileId || release.artistProfileId === form.artistProfileId);
  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_420px]">
    <section className="panel space-y-5 px-4 py-5 sm:px-6"><div><p className="field-label">Authoritative promotion history</p><h2 className="mt-2 text-2xl font-semibold text-ink">Campaigns</h2><p className="mt-2 text-sm text-muted">Confirmed calendar-date intervals are the source of truth. Reporting windows remain evidence only.</p></div>
      <form className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5" onSubmit={(event) => {event.preventDefault(); void load();}}>
        <label className="field-shell"><span className="field-label">Release</span><select className="field-input" value={filters.releaseId} onChange={(e) => setFilters({...filters, releaseId: e.target.value})}><option value="">All</option>{releases.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label>
        <label className="field-shell"><span className="field-label">Platform</span><select className="field-input" value={filters.platform} onChange={(e) => setFilters({...filters, platform: e.target.value})}><option value="">All</option>{["META","INSTAGRAM","TIKTOK","YOUTUBE","EMAIL","OTHER"].map((item) => <option key={item}>{item}</option>)}</select></label>
        <label className="field-shell"><span className="field-label">Status</span><select className="field-input" value={filters.status} onChange={(e) => setFilters({...filters, status: e.target.value})}><option value="">All</option>{["DRAFT","ACTIVE","PAUSED","ENDED","ARCHIVED"].map((item) => <option key={item}>{item}</option>)}</select></label>
        <label className="field-shell"><span className="field-label">Active date</span><input className="field-input" type="date" value={filters.activeDate} onChange={(e) => setFilters({...filters, activeDate: e.target.value})} /></label>
        <label className="field-shell"><span className="field-label">Confirmation</span><select className="field-input" value={filters.confirmationStatus} onChange={(e) => setFilters({...filters, confirmationStatus: e.target.value})}><option value="">All</option>{["CONFIRMED","SUGGESTED","REJECTED","SUPERSEDED"].map((item) => <option key={item}>{item}</option>)}</select></label>
        <button className="action-button-secondary sm:col-span-2 xl:col-span-1" disabled={busy} type="submit">{busy ? <LoaderCircle className="animate-spin" size={15} /> : null} Apply filters</button>
      </form>
      {error ? <div className="state-panel-danger" role="alert"><AlertTriangle size={18} />{error}</div> : null}
      {!data.items.length ? <div className="rounded-xl border border-dashed border-edge p-8 text-center text-sm text-muted">No campaigns match this view.</div> : <div className="space-y-3">{data.items.map((item) => { const confirmed = item.activeIntervals.filter((interval) => interval.confirmationStatus === "CONFIRMED"); const suggested = item.activeIntervals.filter((interval) => interval.confirmationStatus === "SUGGESTED").length; const open = confirmed.some((interval) => !interval.activeEndDate); return <article className="rounded-xl border border-edge bg-input p-4" key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-ink">{item.name}</h3><p className="mt-1 text-sm text-secondary">{item.release.title} · {item.platform} · {item.status}</p></div><Link className="action-button-secondary text-xs" href={`/admin/retention-lab/campaigns/${item.id}`}>Open editor</Link></div><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="status-badge-neutral">{confirmed.length} confirmed interval{confirmed.length === 1 ? "" : "s"}</span>{open ? <span className="status-badge-warning">Open interval</span> : null}{suggested ? <span className="status-badge-warning">{suggested} suggestion{suggested === 1 ? "" : "s"}</span> : null}{item.overlaps.length ? <span className="status-badge-warning">{item.overlaps.length} overlap warning{item.overlaps.length === 1 ? "" : "s"}</span> : null}</div><div className="mt-3 space-y-1 text-xs text-muted">{item.activeIntervals.map((interval, index) => <p key={index}><CalendarRange className="mr-1 inline" size={13} />{interval.activeStartDate} through {interval.activeEndDate || "open"} (inclusive) · {provenance(interval.confirmationStatus)}</p>)}</div><p className="mt-3 text-xs text-muted">Updated {new Date(item.updatedAt).toLocaleString()}</p></article>;})}</div>}
    </section>
    <section className="panel h-fit space-y-4 px-4 py-5 sm:px-6"><div><p className="field-label">New identity</p><h2 className="mt-2 text-xl font-semibold text-ink">Create campaign</h2></div><form className="space-y-3" onSubmit={create}>
      <label className="field-shell"><span className="field-label">Artist</span><select className="field-input" value={form.artistProfileId} onChange={(e) => setForm({...form, artistProfileId: e.target.value, releaseId: ""})}>{artists.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label>
      <label className="field-shell"><span className="field-label">Promoted release</span><select className="field-input" required value={form.releaseId} onChange={(e) => setForm({...form, releaseId: e.target.value})}><option value="">Select release</option>{eligibleReleases.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label>
      <label className="field-shell"><span className="field-label">Campaign name</span><input className="field-input" maxLength={200} required value={form.name} onChange={(e) => setForm({...form, name: e.target.value})} /></label>
      <div className="grid gap-3 sm:grid-cols-2"><label className="field-shell"><span className="field-label">Platform</span><select className="field-input" value={form.platform} onChange={(e) => setForm({...form, platform: e.target.value})}>{["META","INSTAGRAM","TIKTOK","YOUTUBE","EMAIL","OTHER"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="field-shell"><span className="field-label">Objective</span><select className="field-input" value={form.objective} onChange={(e) => setForm({...form, objective: e.target.value})}>{["AWARENESS","TRAFFIC","ENGAGEMENT","CONVERSIONS","STREAMS","PRESAVE","RETARGETING","OTHER"].map((item) => <option key={item}>{item}</option>)}</select></label></div>
      <label className="field-shell"><span className="field-label">Meta / platform identity</span><input className="field-input" maxLength={300} value={form.externalCampaignName} onChange={(e) => setForm({...form, externalCampaignName: e.target.value})} /></label><label className="field-shell"><span className="field-label">External campaign ID</span><input className="field-input" maxLength={200} value={form.externalCampaignId} onChange={(e) => setForm({...form, externalCampaignId: e.target.value})} /></label><label className="field-shell"><span className="field-label">Notes</span><textarea className="field-input min-h-24" maxLength={2000} value={form.notes} onChange={(e) => setForm({...form, notes: e.target.value})} /></label>
      <button className="action-button-primary w-full" disabled={busy || !form.releaseId} type="submit"><Plus size={16} /> Create campaign</button>
    </form></section>
  </div>;
}
