import Link from "next/link";
import {AlertTriangle, CalendarRange} from "lucide-react";

export function ReleaseCampaignTimelineSection({timeline}: {timeline: any}) {
  const suggestions = timeline.campaigns.reduce((count: number, campaign: any) => count + campaign.activeIntervals.filter((item: any) => item.confirmationStatus === "SUGGESTED").length, 0);
  const overlaps = timeline.campaigns.flatMap((campaign: any) => campaign.overlaps || []);
  return <section className="panel space-y-5 px-4 py-5 sm:px-6" id="campaign-timeline"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="field-label">Promotion history</p><h2 className="mt-2 text-2xl font-semibold text-ink">Campaign Timeline</h2><p className="mt-2 max-w-3xl text-sm text-muted">Confirmed paid-promotion intervals and descriptive events only. This section does not calculate listener retention.</p></div><Link className="action-button-secondary text-xs" href="/admin/retention-lab/campaigns">Manage campaigns</Link></div>
    {!timeline.campaigns.length ? <p className="rounded-xl border border-dashed border-edge p-6 text-sm text-muted">No promotion campaign is associated with this release.</p> : <div className="grid gap-3 lg:grid-cols-2">{timeline.campaigns.map((campaign: any) => <article className="rounded-xl border border-edge bg-input p-4" key={campaign.id}><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold text-ink">{campaign.name}</h3><p className="mt-1 text-sm text-secondary">{campaign.platform} · {campaign.status}</p></div><Link className="text-xs font-semibold text-accent hover:underline" href={`/admin/retention-lab/campaigns/${campaign.id}`}>Open</Link></div><div className="mt-3 space-y-1 text-xs text-muted">{campaign.activeIntervals.filter((item: any) => item.confirmationStatus === "CONFIRMED").map((item: any) => <p key={item.id}><CalendarRange className="mr-1 inline" size={13} />{item.activeStartDate} through {item.activeEndDate || "open"} (inclusive) · Confirmed {item.sourceType === "MANUAL" ? "manual" : "from evidence"}</p>)}</div>{campaign.activeIntervals.some((item: any) => item.confirmationStatus === "SUGGESTED") ? <p className="mt-3 status-badge-warning">Suggestion awaiting confirmation</p> : null}</article>)}</div>}
    {timeline.events.length ? <details className="rounded-xl border border-edge bg-input p-4"><summary className="cursor-pointer font-semibold text-ink">Timeline events ({timeline.events.length})</summary><div className="mt-3 space-y-2">{timeline.events.map((event: any) => <p className="text-sm text-secondary" key={event.id}><strong>{event.eventDate}</strong> · {event.title} <span className="text-xs text-muted">({event.source === "SYSTEM_INTERVAL_SYNC" ? "system-generated from confirmed interval" : event.source === "USER_ENTERED" ? "user-entered descriptive event" : event.source.toLowerCase().replaceAll("_", " ")})</span></p>)}</div></details> : null}
    {suggestions ? <div className="state-panel-warning"><AlertTriangle size={18} />{suggestions} suggested interval{suggestions === 1 ? "" : "s"} still require admin confirmation and timezone review.</div> : null}{overlaps.length ? <div className="state-panel-warning"><AlertTriangle size={18} />{overlaps.length} overlap record{overlaps.length === 1 ? "" : "s"}, including concurrent campaigns or other releases published during campaign dates.</div> : null}
  </section>;
}
