"use client";

import Link from "next/link";
import {useState} from "react";
import {AlertTriangle, CheckCircle2, LoaderCircle} from "lucide-react";

import {AdminConfirmDialog} from "@/components/admin-confirm-dialog";
import {SpotifyImportWorkflow, type SpotifyImportPreview} from "@/components/retention-import-center";
import {ErrorState} from "@/components/ui-state";
import {adminFetch, AdminRequestError, getAdminErrorMessage} from "@/lib/admin-errors";
import {formatValidationValue, importErrorCopy} from "@/lib/analytics/import-center-ui";
import type {ArtistOption, RetentionReleaseOption} from "@/lib/analytics/import-center-types";

export type ImportDetailRecord = {
  id: string; source: string; importType: string; originalFilename: string; fileHash: string; normalizationVersion: string;
  artistProfileId: string; artistProfile: {id: string; displayName: string; slug: string}; uploadedByUsername: string; uploadedAt: string; acceptedAt: string | null; status: string;
  detectedPeriodStart: string | null; detectedPeriodEnd: string | null; userConfirmedPeriodStart: string | null; userConfirmedPeriodEnd: string | null; periodDatesUserConfirmed: boolean;
  rowCount: number; acceptedRowCount: number; rejectedRowCount: number; unmatchedRowCount: number; warningCount: number;
  rawFileAvailability: string; rawFileExpiresAt: string | null; rawFileDeletedAt: string | null;
  replacedByImportId: string | null; replacesImportId: string | null; replacedBy: {id: string; status: string} | null; replaces: {id: string; status: string} | null;
  withdrawnAt: string | null; withdrawnById: string | null; withdrawalReason: string;
  validationSummary: Record<string, unknown>; metadata: Record<string, unknown>; dataProvenance: {parserVersion: string | null};
  _count: {artistMetricObservations: number; trackMetricObservations: number; songPeriodSnapshots: number; playlistPeriodSnapshots: number};
};
function dt(value: string | null) { if (!value) return "Not available"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-US", {dateStyle: "medium", timeStyle: "short"}).format(date); }
function text(value: unknown, fallback = "Not available") { return formatValidationValue(value, fallback); }
function Field({label, value}: {label: string; value: unknown}) { return <div className="rounded-lg border border-edge bg-input p-3"><dt className="field-label">{label}</dt><dd className="mt-2 break-words text-sm font-semibold text-ink">{text(value)}</dd></div>; }
function Section({title, children}: {title: string; children: React.ReactNode}) { return <section className="panel px-4 py-5 sm:px-6"><h2 className="text-xl font-semibold text-ink">{title}</h2><div className="mt-4">{children}</div></section>; }

export function RetentionImportDetail({initialImport, artists, releases, canonicalArtistId}: {initialImport: ImportDetailRecord; artists: ArtistOption[]; releases: RetentionReleaseOption[]; canonicalArtistId: string | null}) {
  const [record, setRecord] = useState(initialImport);
  const [withdrawOpen, setWithdrawOpen] = useState(false);
  const [reason, setReason] = useState("");
  const [reprocessPreview, setReprocessPreview] = useState<SpotifyImportPreview | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const validation = record.validationSummary || {};
  const reconciliation = (validation.reconciliation && typeof validation.reconciliation === "object" ? validation.reconciliation : {}) as {entries?: Array<Record<string, unknown>>};
  const parserSummary = validation as {blockingErrors?: unknown[]; fileWarnings?: unknown[]; missingDates?: unknown[]; counts?: Record<string, unknown>; dateRange?: unknown};

  async function refresh() { const response = await adminFetch<{import: ImportDetailRecord}>(`/api/analytics/imports/${record.id}`); setRecord(response.import); }
  async function withdraw() {
    if (!reason.trim()) return;
    setBusy(true); setError(null); setMessage(null);
    try { await adminFetch(`/api/analytics/imports/${record.id}/withdraw`, {method: "POST", headers: {"content-type": "application/json"}, body: JSON.stringify({reason})}); await refresh(); setWithdrawOpen(false); setMessage("Import withdrawn. Normalized history remains preserved and the import is excluded from current analytics."); }
    catch (caught) { setError(getAdminErrorMessage(caught, "The import could not be withdrawn.")); }
    finally { setBusy(false); }
  }
  async function reprocess() {
    setBusy(true); setError(null); setMessage(null);
    try { const preview = await adminFetch<SpotifyImportPreview>(`/api/analytics/imports/${record.id}/reprocess`, {method: "POST"}); setReprocessPreview(preview); setMessage("A new in-memory preview was created. The original import is unchanged and no automatic replacement will occur."); }
    catch (caught) { const code = caught instanceof AdminRequestError ? caught.code : "UNKNOWN"; setError(importErrorCopy(code, getAdminErrorMessage(caught, "The retained raw file could not be reprocessed."))); }
    finally { setBusy(false); }
  }
  return <div className="space-y-6">{message ? <div className="state-panel-success" role="status"><CheckCircle2 aria-hidden="true" size={18} /><p>{message}</p></div> : null}{error ? <ErrorState message={error} /> : null}<Section title="Identity"><dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Import ID" value={record.id} /><Field label="Filename" value={record.originalFilename} /><Field label="Type" value={record.importType.replaceAll("_", " ")} /><Field label="Artist" value={record.artistProfile?.displayName || record.artistProfileId} /><Field label="File hash" value={record.fileHash} /><Field label="Parser version" value={record.dataProvenance?.parserVersion} /><Field label="Normalization" value={record.normalizationVersion} /><Field label="Uploaded by" value={record.uploadedByUsername} /><Field label="Uploaded" value={dt(record.uploadedAt)} /><Field label="Accepted" value={dt(record.acceptedAt)} /><Field label="Status" value={record.status} /></dl></Section>
  <Section title="Coverage and provenance"><dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Detected range" value={record.detectedPeriodStart && record.detectedPeriodEnd ? `${record.detectedPeriodStart} to ${record.detectedPeriodEnd}` : "Not detected"} /><Field label="Confirmed report period" value={record.userConfirmedPeriodStart && record.userConfirmedPeriodEnd ? `${record.userConfirmedPeriodStart} to ${record.userConfirmedPeriodEnd}` : "Not supplied"} /><Field label="Period provenance" value={record.periodDatesUserConfirmed ? "User-entered and confirmed" : "Detected from dated observations"} /><Field label="Rows" value={`${record.rowCount} total · ${record.acceptedRowCount} accepted · ${record.unmatchedRowCount} unmatched · ${record.rejectedRowCount} rejected · ${record.warningCount} warnings`} /><Field label="Artist observations" value={record._count.artistMetricObservations} /><Field label="Track observations" value={record._count.trackMetricObservations} /><Field label="Song snapshots" value={record._count.songPeriodSnapshots} /><Field label="Playlist snapshots" value={record._count.playlistPeriodSnapshots} /><Field label="Missing dates" value={parserSummary.missingDates} /><Field label="Detected date summary" value={parserSummary.dateRange} /></dl></Section>
  <Section title="Validation"><div className="grid gap-3 lg:grid-cols-2"><div className="rounded-xl border border-edge bg-input p-4"><p className="font-semibold text-ink">Blocking errors</p><p className="mt-2 text-sm text-secondary">{text(parserSummary.blockingErrors, "None")}</p></div><div className="rounded-xl border border-edge bg-input p-4"><p className="font-semibold text-ink">Warnings</p><p className="mt-2 text-sm text-secondary">{text(parserSummary.fileWarnings, record.warningCount ? `${record.warningCount} warning row(s); see preserved validation summary.` : "None")}</p></div><div className="rounded-xl border border-edge bg-input p-4"><p className="font-semibold text-ink">Unmatched rows</p><p className="mt-2 text-sm text-secondary">{record.unmatchedRowCount} valid row(s) still need catalog identity.</p>{record.unmatchedRowCount ? <Link className="action-button-secondary mt-3 text-xs" href={`/admin/retention-lab/mappings?import_id=${record.id}`}>Open filtered mapping queue</Link> : null}</div><details className="rounded-xl border border-edge bg-input p-4"><summary className="cursor-pointer font-semibold text-ink">Validation summary details</summary><div className="mt-3 space-y-2 text-xs text-secondary">{Object.entries(validation).filter(([key]) => key !== "reconciliation").map(([key, value]) => <p className="break-words" key={key}><span className="font-mono text-muted">{key}</span>: {text(value)}</p>)}</div></details></div></Section>
  <Section title="Reconciliation"><p className="mb-4 text-sm text-muted">These are comparison checks across available Spotify datasets. They do not represent organic or paid attribution.</p>{reconciliation.entries?.length ? <div className="table-surface mobile-scroll-x"><table className="w-full min-w-[820px] text-left text-sm"><thead><tr>{["Comparison", "Source", "Comparable", "Absolute difference", "Percentage difference", "Severity / availability", "Period"].map((label) => <th className="px-3 py-3 field-label" key={label} scope="col">{label}</th>)}</tr></thead><tbody>{reconciliation.entries.map((entry, index) => <tr className="border-t border-edge" key={`${entry.key}-${index}`}><td className="px-3 py-3 text-ink">{text(entry.key)}</td><td className="px-3 py-3 text-secondary">{text(entry.sourceValue)}</td><td className="px-3 py-3 text-secondary">{text(entry.comparableValue)}</td><td className="px-3 py-3 text-secondary">{text(entry.absoluteDifference)}</td><td className="px-3 py-3 text-secondary">{entry.percentageDifference === null || entry.percentageDifference === undefined ? "Unavailable" : `${entry.percentageDifference}%`}</td><td className="px-3 py-3 text-secondary">{text(entry.severity || entry.status)}</td><td className="px-3 py-3 text-secondary">{text(entry.period || entry.comparisonPeriod)}</td></tr>)}</tbody></table></div> : <p className="text-sm text-muted">No comparable dataset was available for this import period.</p>}</Section>
  <Section title="Lifecycle"><dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Raw-file availability" value={record.rawFileAvailability} /><Field label="Raw-file expiration" value={dt(record.rawFileExpiresAt)} /><Field label="Raw-file deletion" value={record.rawFileDeletedAt ? dt(record.rawFileDeletedAt) : "Not deleted"} /><Field label="Replacement import" value={record.replacedBy?.id || record.replacedByImportId || "None"} /><Field label="Replaced import" value={record.replaces?.id || record.replacesImportId || "None"} /><Field label="Withdrawal actor" value={record.withdrawnById} /><Field label="Withdrawal date" value={dt(record.withdrawnAt)} /><Field label="Withdrawal reason" value={record.withdrawalReason} /></dl><div className="mt-5 flex flex-wrap gap-3"><button className="action-button-secondary" disabled={busy || record.rawFileAvailability !== "AVAILABLE"} onClick={() => void reprocess()} type="button">{busy ? <LoaderCircle aria-hidden="true" className="animate-spin" size={16} /> : null}Reprocess retained file</button><button className="action-button-danger" disabled={busy || record.status !== "IMPORTED"} onClick={() => setWithdrawOpen(true)} type="button">Withdraw import</button><Link className="action-button-secondary" href={`/admin/retention-lab/mappings?import_id=${record.id}`}>Open mapping queue</Link></div>{record.rawFileAvailability !== "AVAILABLE" ? <div className="state-panel-warning mt-4"><AlertTriangle aria-hidden="true" size={18} /><p>Reprocessing is unavailable because the private raw file expired, was deleted, or was never retained. This is non-retryable; normalized analytics data remains.</p></div> : <p className="mt-4 text-sm text-muted">Reprocessing reparses the retained raw file into a new preview. The original import remains unchanged, no automatic replacement occurs, and identical bytes remain subject to global hash rules.</p>}</Section>
  {reprocessPreview ? <SpotifyImportWorkflow artists={artists} canonicalArtistId={canonicalArtistId} initialPreview={reprocessPreview} releases={releases} /> : null}
  <AdminConfirmDialog description="Normalized records remain preserved, but this import will be excluded from current analytics. Replacement links and the complete provenance record remain visible." onClose={() => setWithdrawOpen(false)} open={withdrawOpen} title="Withdraw analytics import"><label className="field-shell"><span className="field-label">Required withdrawal reason</span><textarea className="field-input min-h-28" maxLength={500} onChange={(event) => setReason(event.target.value)} value={reason} /></label><label className="mt-4 flex gap-3 text-sm text-secondary"><input checked={Boolean(reason.trim())} readOnly type="checkbox" /><span>I confirm this is a withdrawal, not deletion, and that normalized history remains preserved.</span></label><div className="mt-5 flex justify-end gap-2"><button className="action-button-secondary" onClick={() => setWithdrawOpen(false)} type="button">Cancel</button><button className="action-button-danger" disabled={!reason.trim() || busy} onClick={() => void withdraw()} type="button">Confirm withdrawal</button></div></AdminConfirmDialog></div>;
}
