import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
const source = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8");
const list = source("components/campaign-timeline-center.tsx"); const creator = source("components/release-campaign-creator.tsx"); const editor = source("components/campaign-timeline-editor.tsx"); const release = source("components/release-campaign-timeline-section.tsx"); const legacyDetail = source("app/admin/(protected)/retention-lab/campaigns/[id]/page.tsx"); const nav = source("components/command-center-nav.tsx");
for (const value of ["Cross-release index", "Platform", "Status", "Active date", "Confirmation", "Open interval", "overlap warning", "Updated", "Open release workspace"]) assert.ok(list.toLowerCase().includes(value.toLowerCase()), `campaign list includes ${value}`);
for (const value of ["Create a campaign for this release", "Campaign name", "Platform", "Objective", "External campaign ID", "Create campaign"]) assert.ok(creator.includes(value), `release creator includes ${value}`);
for (const value of ["Pause campaign", "Resume campaign", "End campaign", "Archive", "Add confirmed interval", "Correct with audit reason", "Confirm suggestion", "Reject suggestion", "BUDGET_CHANGED", "CREATIVE_CHANGED", "AUDIENCE_CHANGED", "ORGANIC_CONTENT_POSTED", "Suggested from Meta spend", "System-generated from confirmed interval", "User-entered descriptive event", "Current suggestion evidence", "Superseded evidence", "Observed spend:", "Suggested period:", "Stable-ID promotion links", "AD before AD SET before CAMPAIGN", "Names never create a link", "Spend is descriptive and unallocated", "immutable history preserved"]) assert.ok(editor.includes(value), `editor supports ${value}`);
assert.ok(release.includes("Promotion &amp; Retention") && release.includes("Campaign Timeline") && release.includes("Suggestion awaiting confirmation") && release.includes("overlap record") && release.includes("CampaignTimelineEditor"));
assert.ok(legacyDetail.includes("redirect(") && legacyDetail.includes("manageCampaignId") && legacyDetail.includes("#campaign-management"), "legacy campaign details redirect to the canonical release workspace");
assert.ok(nav.includes("/admin/retention-lab/campaigns"));
for (const file of [list, creator, editor, release]) assert.ok(!/baseline|lift retained|campaign peak|post-campaign floor|paid-dependency/i.test(file), "Stage 6 UI must not contain retention calculations");
for (const file of [list, creator, editor, release]) assert.doesNotMatch(file, /recharts|retention-timeline-chart/i, "Campaign management must remain independent from the Stage 9 chart bundle");
console.log("Campaign timeline UI deterministic checks passed.");
