import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {Prisma} from "@prisma/client";
import {gunzipSync} from "node:zlib";
import {prisma} from "../lib/db/prisma";
import {createDatabaseSnapshotArtifact} from "../lib/backups/snapshot";
import {addCampaignEvent, addCampaignInterval, correctCampaignEvent, correctCampaignInterval, createPromotionCampaign, generateMetaIntervalSuggestions, listPromotionCampaigns, readCampaignOverlaps, readPromotionCampaign, resolveCampaignSuggestion, updatePromotionCampaign} from "../lib/analytics/campaign-timeline-service";

const runId = randomUUID(); const actorId = `campaign-admin-${runId}`; const artistId = `campaign-artist-${runId}`; const otherArtistId = `campaign-other-artist-${runId}`; const releaseId = `campaign-release-${runId}`; const otherReleaseId = `campaign-other-release-${runId}`; const mismatchReleaseId = `campaign-mismatch-release-${runId}`; const campaignIds: string[] = []; const batchIds: string[] = [];
const actor = {userId: actorId, username: "campaign-test-admin"}; const now = new Date("2026-08-03T12:00:00.000Z");

async function expectCode(action: () => Promise<unknown>, code: string) { await assert.rejects(action, (error: unknown) => { assert.equal((error as {code?: string}).code, code); return true; }); }
async function cleanup() { if (campaignIds.length) { await prisma.campaignAuditEvent.deleteMany({where: {campaignId: {in: campaignIds}}}); await prisma.campaignTimelineEvent.updateMany({where: {campaignId: {in: campaignIds}}, data: {supersedesEventId: null}}); await prisma.campaignTimelineEvent.deleteMany({where: {campaignId: {in: campaignIds}}}); await prisma.campaignActiveInterval.updateMany({where: {campaignId: {in: campaignIds}}, data: {supersedesIntervalId: null}}); await prisma.campaignActiveInterval.deleteMany({where: {campaignId: {in: campaignIds}}}); await prisma.campaignEvidence.deleteMany({where: {campaignId: {in: campaignIds}}}); await prisma.promotionCampaign.deleteMany({where: {id: {in: campaignIds}}}); } await prisma.adCreativeReport.deleteMany({where: {importBatchId: {in: batchIds}}}); await prisma.adImportBatch.deleteMany({where: {id: {in: batchIds}}}); await prisma.release.deleteMany({where: {id: {in: [releaseId, otherReleaseId, mismatchReleaseId]}}}); await prisma.artistProfile.deleteMany({where: {id: {in: [artistId, otherArtistId]}}}); await prisma.adminUser.deleteMany({where: {id: actorId}}); }

async function main() {
  await cleanup();
  await prisma.adminUser.create({data: {id: actorId, username: actor.username, createdAt: now, updatedAt: now}});
  await prisma.artistProfile.createMany({data: [{id: artistId, slug: `campaign-artist-${runId}`, displayName: "Campaign Artist", draftUpdatedAt: now, createdAt: now, updatedAt: now}, {id: otherArtistId, slug: `campaign-other-${runId}`, displayName: "Other Artist", draftUpdatedAt: now, createdAt: now, updatedAt: now}]});
  await prisma.release.createMany({data: [{id: releaseId, slug: releaseId, title: "Campaign Release", primaryArtistProfileId: artistId, releaseDate: new Date("2026-06-02T00:00:00.000Z"), createdOn: now, updatedOn: now}, {id: otherReleaseId, slug: otherReleaseId, title: "Other Release", primaryArtistProfileId: artistId, releaseDate: new Date("2026-06-04T00:00:00.000Z"), createdOn: now, updatedOn: now}, {id: mismatchReleaseId, slug: mismatchReleaseId, title: "Mismatch Release", primaryArtistProfileId: otherArtistId, createdOn: now, updatedOn: now}]});
  await expectCode(() => createPromotionCampaign({actor, artistProfileId: artistId, releaseId: "missing", platform: "META", name: "Missing", objective: "STREAMS"}), "CAMPAIGN_RELEASE_REQUIRED");
  await expectCode(() => createPromotionCampaign({actor, artistProfileId: artistId, releaseId: mismatchReleaseId, platform: "META", name: "Mismatch", objective: "STREAMS"}), "CAMPAIGN_ARTIST_MISMATCH");
  const first = await createPromotionCampaign({actor, artistProfileId: artistId, releaseId, platform: "META", name: "Launch", objective: "STREAMS", externalCampaignName: "Launch Meta", now}); campaignIds.push(first.campaignId);
  const second = await createPromotionCampaign({actor, artistProfileId: artistId, releaseId, platform: "META", name: "Retarget", objective: "RETARGETING", now}); campaignIds.push(second.campaignId);
  const third = await createPromotionCampaign({actor, artistProfileId: artistId, releaseId: otherReleaseId, platform: "TIKTOK", name: "Other Release Push", objective: "AWARENESS", now}); campaignIds.push(third.campaignId);
  assert.equal((await listPromotionCampaigns({releaseId})).total, 2, "multiple campaigns per release are supported");
  const one = await addCampaignInterval(first.campaignId, {actor, activeStartDate: "2026-06-01", activeEndDate: "2026-06-03", timezone: "America/New_York", now});
  await expectCode(() => addCampaignInterval(first.campaignId, {actor, activeStartDate: "2026-06-03", activeEndDate: "2026-06-04", timezone: "UTC"}), "CAMPAIGN_INTERVAL_OVERLAP");
  await expectCode(() => addCampaignInterval(first.campaignId, {actor, activeStartDate: "2026-06-05", activeEndDate: "2026-06-04", timezone: "UTC"}), "CAMPAIGN_INTERVAL_INVALID");
  await addCampaignInterval(first.campaignId, {actor, activeStartDate: "2026-06-04", activeEndDate: "2026-06-05", timezone: "America/New_York", now});
  const openInterval = await addCampaignInterval(first.campaignId, {actor, activeStartDate: "2026-06-10", timezone: "America/New_York", now});
  await expectCode(() => addCampaignInterval(first.campaignId, {actor, activeStartDate: "2026-06-12", timezone: "UTC"}), "CAMPAIGN_INTERVAL_OVERLAP");
  await expectCode(() => updatePromotionCampaign(first.campaignId, {actor, status: "PAUSED"}), "CAMPAIGN_CONFLICT");
  await updatePromotionCampaign(first.campaignId, {actor, status: "ACTIVE", now});
  await expectCode(() => updatePromotionCampaign(first.campaignId, {actor, status: "ENDED"}), "CAMPAIGN_CONFLICT");
  const detail = await readPromotionCampaign(first.campaignId); const events = detail.timelineEvents.filter((item: any) => item.confirmationStatus === "CONFIRMED"); assert.ok(events.some((item: any) => item.eventType === "RELEASE_PUBLISHED")); assert.ok(events.some((item: any) => item.eventType === "CAMPAIGN_STARTED")); assert.ok(events.some((item: any) => item.eventType === "CAMPAIGN_PAUSED")); assert.ok(events.some((item: any) => item.eventType === "CAMPAIGN_RESUMED"));
  const corrected = await correctCampaignInterval(first.campaignId, one.intervalId, {actor, activeStartDate: "2026-05-31", activeEndDate: "2026-06-03", timezone: "America/New_York", reason: "Corrected from platform receipt", now}); assert.notEqual(corrected.intervalId, one.intervalId); const history = await readPromotionCampaign(first.campaignId); assert.ok(history.activeIntervals.some((item: any) => item.id === one.intervalId && item.confirmationStatus === "SUPERSEDED"));
  const budget = await addCampaignEvent(first.campaignId, {actor, eventType: "BUDGET_CHANGED", eventDate: "2026-06-02", timezone: "America/New_York", title: "Budget increased", now}); await addCampaignEvent(first.campaignId, {actor, eventType: "CREATIVE_CHANGED", eventDate: "2026-06-03", timezone: "America/New_York", title: "Hook B launched", now}); await addCampaignEvent(first.campaignId, {actor, eventType: "AUDIENCE_CHANGED", eventDate: "2026-06-04", timezone: "America/New_York", title: "Retargeting expanded", now}); await addCampaignEvent(first.campaignId, {actor, eventType: "ORGANIC_CONTENT_POSTED", eventDate: "2026-06-04", timezone: "America/New_York", title: "Reel posted", now}); await addCampaignEvent(first.campaignId, {actor, eventType: "OTHER_RELEASE_PUBLISHED", eventDate: "2026-06-04", timezone: "UTC", title: "Other release published", now}); await addCampaignEvent(first.campaignId, {actor, eventType: "MANUAL_NOTE", eventDate: "2026-06-05", timezone: "UTC", title: "Manual context", now}); const eventCorrection = await correctCampaignEvent(first.campaignId, budget.eventId, {actor, eventDate: "2026-06-02", timezone: "America/New_York", title: "Budget doubled", reason: "Receipt clarified amount", now}); assert.notEqual(eventCorrection.eventId, budget.eventId);
  await addCampaignInterval(second.campaignId, {actor, activeStartDate: "2026-06-03", activeEndDate: "2026-06-04", timezone: "UTC", now}); await addCampaignInterval(third.campaignId, {actor, activeStartDate: "2026-06-04", activeEndDate: "2026-06-06", timezone: "UTC", now}); const overlaps = await readCampaignOverlaps(first.campaignId, {futureWindowEndDate: "2026-06-04"}); assert.ok(overlaps.some((item) => item.type === "SAME_RELEASE_CAMPAIGN")); assert.ok(overlaps.some((item) => item.type === "DIFFERENT_RELEASE_CAMPAIGN")); assert.ok(overlaps.some((item) => item.type === "OTHER_RELEASE_PUBLISHED")); assert.ok(overlaps.some((item) => item.type === "OTHER_RELEASE_IN_FUTURE_WINDOW")); assert.ok(overlaps.some((item) => item.type === "OPEN_CAMPAIGN"));
  await correctCampaignInterval(first.campaignId, openInterval.intervalId, {actor, activeStartDate: "2026-06-10", activeEndDate: "2026-06-12", timezone: "America/New_York", reason: "Campaign ended", now}); await updatePromotionCampaign(first.campaignId, {actor, status: "ENDED", now}); assert.ok((await readPromotionCampaign(first.campaignId)).timelineEvents.some((item: any) => item.confirmationStatus === "CONFIRMED" && item.eventType === "CAMPAIGN_ENDED"));
  const dailyBatchId = `campaign-batch-daily-${runId}`; const windowBatchId = `campaign-batch-window-${runId}`; batchIds.push(dailyBatchId, windowBatchId); await prisma.adImportBatch.create({data: {id: dailyBatchId, name: "Daily evidence", releaseId, reportingStart: new Date("2026-07-01T00:00:00.000Z"), reportingEnd: new Date("2026-07-06T00:00:00.000Z"), createdAt: now, updatedAt: now}}); for (const [day, spend] of [["01", 5], ["02", 0], ["03", 4], ["06", 3]] as const) await prisma.adCreativeReport.create({data: {id: `campaign-report-${day}-${runId}`, importBatchId: dailyBatchId, releaseId, campaignName: "Launch Meta", adName: `Ad ${day}`, reportingStart: new Date(`2026-07-${day}T00:00:00.000Z`), reportingEnd: new Date(`2026-07-${day}T00:00:00.000Z`), spend, createdAt: now, updatedAt: now}}); await prisma.adImportBatch.create({data: {id: windowBatchId, name: "Reporting only", releaseId, reportingStart: new Date("2026-07-01T00:00:00.000Z"), reportingEnd: new Date("2026-07-28T00:00:00.000Z"), createdAt: now, updatedAt: now, reports: {create: {id: `campaign-window-report-${runId}`, releaseId, campaignName: "Launch Meta", adName: "Window ad", reportingStart: new Date("2026-07-01T00:00:00.000Z"), reportingEnd: new Date("2026-07-28T00:00:00.000Z"), spend: 20, createdAt: now, updatedAt: now}}}});
  const suggestions = await generateMetaIntervalSuggestions(first.campaignId, actor, now); assert.equal(suggestions.created, 2, "explicit zero day splits suggestions while missing days do not"); assert.equal(suggestions.evidenceOnly, 1, "multi-day reporting window creates evidence only"); const afterSuggestions = await readPromotionCampaign(first.campaignId); const pending = afterSuggestions.activeIntervals.filter((item: any) => item.confirmationStatus === "SUGGESTED"); assert.equal(pending.length, 2); assert.ok(pending.every((item: any) => item.timezone === "UNCONFIRMED")); await resolveCampaignSuggestion(first.campaignId, pending[0].id, {actor, action: "CONFIRM", activeStartDate: "2026-07-01", activeEndDate: "2026-07-01", timezone: "America/New_York", reason: "Confirmed against Ads Manager", now}); await resolveCampaignSuggestion(first.campaignId, pending[1].id, {actor, action: "REJECT", reason: "Account export was incomplete", now}); await expectCode(() => resolveCampaignSuggestion(first.campaignId, pending[1].id, {actor, action: "REJECT", reason: "again"}), "CAMPAIGN_SUGGESTION_ALREADY_RESOLVED");
  await assert.rejects(() => prisma.release.delete({where: {id: releaseId}}), (error: unknown) => error instanceof Prisma.PrismaClientKnownRequestError && ["P2003", "P2014"].includes(error.code), "campaign release deletion must be restricted");
  await updatePromotionCampaign(second.campaignId, {actor, status: "ARCHIVED", reason: "Test archive", now}); await expectCode(() => addCampaignInterval(second.campaignId, {actor, activeStartDate: "2026-08-01", timezone: "UTC"}), "CAMPAIGN_ARCHIVED");
  const audited = await readPromotionCampaign(first.campaignId); assert.ok(audited.auditEvents.some((item: any) => item.action === "INTERVAL_CORRECTED" && item.reason)); assert.ok(audited.auditEvents.some((item: any) => item.action === "SUGGESTION_REJECTED"));
  const artifact = await createDatabaseSnapshotArtifact(); const snapshot = JSON.parse(gunzipSync(artifact.buffer).toString("utf8")); for (const key of ["promotionCampaigns", "campaignEvidence", "campaignActiveIntervals", "campaignTimelineEvents", "campaignAuditEvents"]) assert.ok(Array.isArray(snapshot[key]) && snapshot[key].length > 0, `backup snapshot includes ${key}`);
  console.log("Campaign timeline deterministic model, interval, event, evidence, overlap, and audit checks passed.");
}
main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(async () => { await cleanup(); await prisma.$disconnect(); });
