import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
const source = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8");
const list = source("components/campaign-timeline-center.tsx"); const editor = source("components/campaign-timeline-editor.tsx"); const release = source("components/release-campaign-timeline-section.tsx"); const nav = source("components/command-center-nav.tsx");
for (const value of ["Campaign name", "Promoted release", "Platform", "Status", "Active date", "Confirmation", "Open interval", "overlap warning", "Updated"]) assert.ok(list.toLowerCase().includes(value.toLowerCase()), `campaign list includes ${value}`);
for (const value of ["Pause campaign", "Resume campaign", "End campaign", "Archive", "Add confirmed interval", "Correct with audit reason", "Confirm suggestion", "Reject suggestion", "BUDGET_CHANGED", "CREATIVE_CHANGED", "AUDIENCE_CHANGED", "ORGANIC_CONTENT_POSTED", "Suggested from Meta spend", "System-generated from confirmed interval", "User-entered descriptive event", "Current suggestion evidence", "Superseded evidence", "Observed spend:", "Suggested period:", "Stable-ID promotion links", "AD before AD SET before CAMPAIGN", "Names never create a link", "Spend is descriptive and unallocated", "immutable history preserved"]) assert.ok(editor.includes(value), `editor supports ${value}`);
assert.ok(release.includes("Campaign Timeline") && release.includes("Suggestion awaiting confirmation") && release.includes("overlap record")); assert.ok(nav.includes("/admin/retention-lab/campaigns"));
for (const file of [list, editor, release]) assert.ok(!/baseline|lift retained|campaign peak|post-campaign floor|paid-dependency/i.test(file), "Stage 6 UI must not contain retention calculations");
for (const file of [list, editor, release]) assert.doesNotMatch(file, /recharts|retention-timeline-chart/i, "Campaign management must remain independent from the Stage 9 chart bundle");
console.log("Campaign timeline UI deterministic checks passed.");
